


spring:
  application:
    name : "food-service"
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: "{cipher}cc4b5dc09f4ed33888f7c7a22a20cde3c86d12d0348ba2436a3d3659f8eabd63"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  # eureka congiguration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
    env:
      enabled: true






