
server.port=9091

# actuator config
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

#spring.datasource.url=jdbc:postgresql://localhost:5432/restaurantdb?TimeZone=Asia/Kolkata
#spring.datasource.username=user
#spring.datasource.password=user123
#spring.datasource.hikari.data-source-properties.TimeZone=Asia/Kolkata
#spring.jackson.time-zone=Asia/Kolkata
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# configure eureka client

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname= localhost
eureka.client.registry-with-eureka=true
eureka.client.fetch-registry=true
