
server.port=9091
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurantdb?TimeZone=Asia/Kolkata
spring.datasource.username=user
spring.datasource.password="{cipher}5937c82ff8f30e50042acbe13943f4cce18b364b1c7f617edf73a127b63fbd04"
spring.datasource.hikari.data-source-properties.TimeZone=Asia/Kolkata
spring.jackson.time-zone=Asia/Kolkata
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
info.app.name=restaurant-service
info.app.description=this is restaurant service prod env 
info.app.version=1.0 prod
# configure eureka client

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname= localhost
eureka.client.registry-with-eureka=true
eureka.client.fetch-registry=true
