
server.port=9091

# actuator config
management.endpoints.web.exposure.include=*
management.info.env.enabled=true


# configure eureka client

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname= localhost
eureka.client.registry-with-eureka=true
eureka.client.fetch-registry=true
